name: sigma-crypto-ascend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - plotly
  - jupyter
  - pip
  - pip:
      - ccxt
      - vectorbt
      - quantstats
      - nautilus_trader
